resources:
    med:
        cpu: 4
        mem: 16000
        time: "02:00:00"
    ram:
        cpu: 2
        mem: 8000
        time: "04:00:00"
koverage:
    args:
        output: "koverage.out/"
        result: "koverage.out/results/"
        reads: "test/reads/"
        ref: "test/ref.fa"
        log: "koverage.out/logs/"
        log_file: "koverage.out/koverage.log"
        bench: "koverage.out/bench/"
        temp: "koverage.out/temp/"
        paf_dir: "koverage.out/pafs/"
        bin_width: 100
        kmer_max: 5000
        kmer_min: 50
        kmer_sample: 100
        kmer_size: 25
        minimap: sr
        pafs: false
        report: true
        report_max_ctg: 1000
    container:
        coverm:
            "oras://quay.io/beardymcjohnface/koverage_coverm:0.0.1"
        minimap:
            "oras://quay.io/beardymcjohnface/koverage_minimap:0.0.1"
        jellyfish:
            "oras://quay.io/beardymcjohnface/koverage_jellyfish:0.0.1"
        report:
            "oras://quay.io/beardymcjohnface/koverage_report:0.0.1"
    envmodules:
        # FOR USE WITH --use-envmodules
        # THESE NEED TO BE AVAILABLE ON YOUR SYSTEM, UPDATE VERSIONS ACCORDINGLY
        # TALK TO YOUR HPC SYSADMINS IF YOU NEED THEM INSTALLED, OR USE CONDA OR APPTAINER/SINGULARITY/DOCKER/ETC INSTEAD
        coverm:
            - "coverm/0.6.1"
        jellyfish:
            - "jellyfish/2.2.10"
        minimap:
            - "minimap2/2.20"
            - "samtools/1.13"
        report:
            - "python/3.13"
            - "pandas"
            - "plotly"
            - "datapane"
    params:
        jellyfish:
            -C 
            -s 1G 
            -c 2 
            --out-counter-len=2 
            -L 2
        coverm:
            -m count
            -m rpkm
            -m tpm
            -m mean
            -m covered_fraction
            -m variance